# Generated by Django 4.0.3 on 2022-03-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='placement',
        ),
        migrations.AddField(
            model_name='placement',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.placement', verbose_name='Пациент'),
            preserve_default=False,
        ),
    ]
