# Generated by Django 4.0.3 on 2022-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_exempt_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ext_staff',
            field=models.BooleanField(default=False, verbose_name='Приглашенный специалист'),
        ),
    ]
