# Generated by Django 4.0.3 on 2022-03-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_staff_ext_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.specialization', verbose_name='Специализация'),
        ),
    ]
