# Generated by Django 4.0.3 on 2022-03-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_service_cost_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exempt',
            name='exempt_tнpe',
            field=models.CharField(max_length=60, verbose_name='Название льготы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.specialization', verbose_name='Специализация'),
        ),
    ]
