# Generated by Django 4.0.3 on 2022-03-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_exempt_exempt_tнpe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exempt',
            old_name='exempt_tнpe',
            new_name='exempt_type',
        ),
    ]
