# Generated by Django 4.0.3 on 2022-03-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_patient_policy_number_alter_exempt_exempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='policy_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.insurancepolicy', verbose_name='Номер страхового полиса'),
        ),
    ]
