# Generated by Django 4.0.3 on 2022-03-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_patient_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underwriter',
            name='comp_address',
            field=models.CharField(max_length=150, verbose_name='Адрес страховой компании'),
        ),
    ]
