# Generated by Django 4.0.3 on 2022-03-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_patient_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='underwriter',
            new_name='exempt',
        ),
    ]
