# Generated by Django 4.0.3 on 2022-03-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_remove_placement_exempt_remove_placement_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор посещения')),
                ('date_start', models.DateTimeField(verbose_name='Дата помещения в стационар')),
                ('date_stop', models.DateTimeField(verbose_name='Дата выписки из стационара')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость лечения всего курса')),
                ('summa', models.PositiveIntegerField(verbose_name='К оплате')),
                ('comment', models.TextField(max_length=200, verbose_name='Расшфировка')),
                ('exempt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.exempt', verbose_name='Льгота')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.placement', verbose_name='Пациент')),
                ('services', models.ManyToManyField(to='hospital.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Посещение стационара',
                'verbose_name_plural': 'Посещения стационаров',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Номер карточки пациента')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО пациента')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес пациента')),
                ('district', models.CharField(max_length=20, verbose_name='Район города, где проживает')),
                ('year', models.CharField(max_length=4, verbose_name='Год рождения пациента')),
                ('sign', models.BooleanField(default=False, verbose_name='Работник предприятия (да/нет)')),
                ('department', models.CharField(blank=True, max_length=40, verbose_name='Отдел, в котором работает')),
                ('policy_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.insurancepolicy', verbose_name='Номер страхового полиса')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
