# Generated by Django 4.0.3 on 2022-03-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_placement_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient', verbose_name='Пациент'),
        ),
    ]
