# Generated by Django 4.0.3 on 2022-03-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_placement_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='services',
            field=models.ManyToManyField(default=0, to='hospital.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='summa',
            field=models.PositiveIntegerField(default=0, verbose_name='К оплате'),
        ),
    ]
