# Generated by Django 4.0.3 on 2022-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_placement_services_alter_placement_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость лечения всего курса'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='services',
            field=models.ManyToManyField(to='hospital.service', verbose_name='Услуги'),
        ),
    ]
