# Generated by Django 4.0.3 on 2022-03-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_placement_cost_alter_placement_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='policy_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.insurancepolicy', verbose_name='Номер страхового полиса'),
        ),
    ]
